name: rhythm_metronome
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.4.4+4

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  sleek_circular_slider: ^2.1.0
  url_launcher: ^6.3.2
  wakelock_plus: ^1.4.0 # Replaces wakelock
  shared_preferences: ^2.5.4
  fluttertoast: ^9.0.0
  # $loading 组件
  flutter_easyloading: ^3.0.5
  flutter_mobx: ^2.3.0
  mobx: ^2.6.0
  # mobx: ^2.0.0-nullsafety.2
  # flutter_mobx: ^2.0.0-nullsafety.0
  audioplayers: ^6.5.1
  record: ^6.2.0
  path_provider: ^2.1.5
  uuid: ^4.5.2
  # 这个Flutter插件提供了一个API，用于查询有关应用程序包的信息。
  package_info_plus: ^9.0.0 # Replaces package_info
  # 桌面图标长按 App Shortcuts
  quick_actions: ^1.1.0
  image_picker: ^1.1.2
dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.10.5
  mobx_codegen: ^2.7.6

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/images/
